### ISSUE TITLE
Long content can break review layout

### ISSUE THREAD

**Issue by getdatakick** [getdatakick/revws#96]
Fix is to add this css rule:

```css
.revws-review-content {
  word-break: break-word;
}
```

It's also necessary to fix the email templates, as they are affected as well
